LUTECE-2103 : fix generated keys with mysql connectorj when called with NO_GENERATED_KEYS
connectorj mysql throws an exception:
java.sql.SQLException: Generated keys not requested. You need to specify Statement.RETURN_GENERATED_KEYS to Statement.executeUpdate(), Statement.executeLargeUpdate() or Connection.prepareStatement().